### ISSUE TITLE
4. Teacher Course List----5 points

### ISSUE THREAD

**Issue by Helen2hang** [Weieiei/ConULearn#129]
As a teacher, I want to see all the courses that I have created so that I can makes quizzes and announcements for the appropriate courses.

_Risk: High Risk, High Value_
High risk because must access the database to get the courses created and display them on the dashboard. 
High value because without the courses' button, the teacher will not be able to makes quizzes and announcements for each classes.
Priority: Do after creation of form

_Tasks_
Task 4.1 Make the courses appear on the dashboard after course creation 
- Get the data and display the courses button in the teacher dashboard.---Alex (2h)

**Comment by z-alex** [comment]
The task has been completed. Here's a little preview:
![capture](https://cloud.githubusercontent.com/assets/25252079/22921276/e38dbe20-f266-11e6-8051-413c04b933b5.PNG)
