### ISSUE TITLE
Glass panel for the sign in and sign up 

### ISSUE THREAD

**Issue by Weieiei** [Weieiei/ConULearn#61]
<img width="1280" alt="screen shot 2017-01-31 at 6 05 19 pm" src="https://cloud.githubusercontent.com/assets/17327871/22488423/e522e490-e7df-11e6-9191-1e12872f4be4.png">
Something like this.

**Comment by Carbonec2** [comment]
Since we are finally doing 2 dashboards, and since those dashboard are only containing content that is accessible to a logged-in user (See discussion #65), this feature is not relevant anymore.
