### ISSUE TITLE
Discussion of the Creation of the dashboard 

### ISSUE THREAD

**Issue by Weieiei** [Weieiei/ConULearn#65]
<img width="1280" alt="screen shot 2017-01-31 at 6 49 56 pm" src="https://cloud.githubusercontent.com/assets/17327871/22489580/385bd42c-e7e6-11e6-8dca-af10c9322f6f.png">

Easy access.

**Comment by Helen2hang** [comment]
Updated version
![dahsboardforonecourse](https://cloud.githubusercontent.com/assets/25255911/22954823/b0c17ce0-f2e6-11e6-8dbe-237bd97d5fea.png)
