### ISSUE TITLE
 1. Registration form for users----1 point

### ISSUE THREAD

**Issue by Weieiei** [Weieiei/ConULearn#89]
As a user, I should be able to select between a student or teacher account when I sign up, so that I can have the right privileges.

_Risk: Low Risk, High Value_
The tasks are not so difficult to implement and should not pose any problems, however they are of  high value because of the fact that our main feature for this sprint is **course creation** which should only be available to teachers and not students. Therefore, it is very important to manage account privileges by giving users selection during registration.
Priority: Do before course creation- only teachers will be able to create a course

_Tasks_
Task 1.1: Front-end design (45min)----Robert
- Put radio buttons in the registration form

Task 1.2: Back-end (2h)----Alex
-Integrate HTML with the mySQL

Task 1.3: Test (1h)----Wei
Task 1.4 Test back-end ----Lunecy

**Comment by z-alex** [comment]
Task 1.1 and 1.2 are done. #99

**Comment by Weieiei** [comment]
Tested already, and it works perfectly.
