### ISSUE TITLE
3. Course Creation Form ----3 points

### ISSUE THREAD

**Issue by Weieiei** [Weieiei/ConULearn#91]
As a teacher, I want to create a course so that students can register to it.

_Risk: High Risk, High Value_
The course creation is the central feature of this sprint. Before being able to create quizzes, post announcements etc. a teacher needs to be able to create the course. Storing the information needs particular attention and should be done correctly to not cause any issues in the future. 
Priority: Do once account privileges are done

_Tasks_
Task 3.1Front-end: Form design (2h)
-Course Name, ID and description----Orel
-Submit button----Orel
-CSS for the form----Helen

Task 3.2 Back-end: Store information in SQL (2h)----Alex

Task 3.3 Test (1h)----Wei

Task 3.4 Test back-end----Lunecy

**Comment by Helen2hang** [comment]
![createform](https://cloud.githubusercontent.com/assets/25255911/22921648/8a382eee-f268-11e6-8045-afcd4b0e7ae2.png)

**Comment by Helen2hang** [comment]
![createform](https://cloud.githubusercontent.com/assets/25255911/22921685/a42a26c2-f268-11e6-8561-6b3de7200d59.png)

**Comment by Weieiei** [comment]
Tested already, and it worked perfectly.
